### ISSUE TITLE
Use on Android without Play services

### ISSUE THREAD

**Issue by Rudloff** [kort/kort-native#62]
Hello,

I'm using Android 6.0.1 without Play services.

I get an error when I open the app:
![screenshot_20180522-175657](https://user-images.githubusercontent.com/840125/40374790-1437a26c-5dea-11e8-9ca3-f34887bbab64.png)

Then the app crashes:
```
05-22 17:57:23.007 28934 28970 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
05-22 17:57:23.007 28934 28970 E AndroidRuntime: Process: ch.hsr.kort, PID: 28934
05-22 17:57:23.007 28934 28970 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.toString()' on a null object reference
05-22 17:57:23.007 28934 28970 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1485)
05-22 17:57:23.007 28934 28970 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:3963)
05-22 17:57:23.007 28934 28970 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:3924)
05-22 17:57:23.007 28934 28970 E AndroidRuntime: 	at com.google.android.gms.common.internal.zzi$1.zzasn(Unknown Source)
05-22 17:57:23.007 28934 28970 E AndroidRuntime: 	at com.google.android.gms.common.internal.zzi.onClick(Unknown Source)
05-22 17:57:23.007 28934 28970 E AndroidRuntime: 	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:163)
05-22 17:57:23.007 28934 28970 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-22 17:57:23.007 28934 28970 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
05-22 17:57:23.007 28934 28970 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
05-22 17:57:23.007 28934 28970 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
05-22 17:57:23.011  1813  1898 W ActivityManager:   Force finishing activity ch.hsr.kort/.MainActivity
```

**Comment by sfkeller** [comment]
The Kort native app (React-Native) need Google Play for location services as a dependency which cannot be replace without substantial programming. Any pull requests are welcome.
